site_name: hearme AI Wiki
docs_dir: docs
theme:
  name: material
  favicon: wiki/favicon.ico
  logo: wiki/logo.png

markdown_extensions:
  - attr_list

nav:
  - Index: wiki/index.md
  - Topics:
    - AI Fundamental: 
      - AI lanscape: wiki/topics/ai_landscape.md
      - Generative AI: wiki/topics/llm.md
      - Self-Learning: wiki/topics/self_learning.md

    - Building AI applications:
      - AI Pipeline: wiki/topics/Building_AI_applications.md
      - Data processing: wiki/topics/Data_processing.md
      - Chunking document: wiki/topics/chunking_document.md
      - AI Applications: wiki/topics/ai_applications.md
    - AI Agents:
      - Overview: wiki/topics/ai_agents.md
      - Building Agent Apps: wiki/topics/building_agent_apps.md
      - Agent Skills: wiki/topics/agent_skills.md
      - AI Coding Agents: wiki/topics/builder_agents.md
      - Orchestrator Agent: wiki/topics/orchestrator_agent.md
      - Personal Agent: wiki/topics/personal_agent.md
      - Research Agents: wiki/topics/Research_agents.md

  - Summary sources: wiki/sources/index.md
  - Entities: wiki/entities/index.md
  - Concepts: wiki/concepts/index.md
  - Raw sources: raw/index.md
  - Log: wiki/log.md