site_name: hearme AI Wiki
docs_dir: docs
theme:
  name: material
  favicon: wiki/favicon.ico
  logo: wiki/logo.png

markdown_extensions:
  - attr_list

nav:
  - Index: wiki/index.md
  - Topics:
    - AI Fundamental: 
      - AI lanscape: wiki/topics/ai_landscape.md
      - Generative AI: wiki/topics/llm.md
    - Building AI applications:
      - AI Pipeline: wiki/topics/Building_AI_applications.md
      - Data processing: wiki/topics/Data_processing.md
      - Building AI agents: wiki/topics/Building_Agents.md
    - AI Agents:
      - Overview: wiki/topics/agent_applications.md
      - Builder Agents: wiki/topics/builder_agents.md
      - Personal Agent: wiki/topics/personal_agent.md

  - Sources:
    - wiki/sources/turboquant.md
    - wiki/sources/scrapling.md
    - wiki/sources/strix.md
    - wiki/sources/hermes_agent.md
    - wiki/sources/claude_mem.md
    - wiki/sources/multica.md
    - wiki/sources/opendataloader_pdf.md
    - wiki/sources/medgemma.md
    - wiki/sources/qwenpaw.md
    - wiki/sources/llm_optimization_72_techniques.md
    - wiki/sources/liteparse.md
    - wiki/sources/autoskills.md
    - wiki/sources/autoresearchclaw.md
    - wiki/sources/agentic_ai_big_picture.md
  - Entities:
    - wiki/entities/aiming_lab.md
    - wiki/entities/nous_research.md
    - wiki/entities/autoskills.md
    - wiki/entities/midudev.md
    - wiki/entities/skills_sh.md
    - wiki/entities/multica_ai.md
    - wiki/entities/opendataloader_project.md
    - wiki/entities/strix.md
    - wiki/entities/thedotmack.md
    - wiki/entities/agentscope_team.md
    - wiki/entities/run_llama.md
    - wiki/entities/google_health.md
  - Concepts:
    - wiki/concepts/ai_agent_skills.md
  - Log: wiki/log.md